INSERT INTO persons (id,band_role, first_name, last_name, band) VALUES
(nextval('persons_id_seq'),'R','James','Hetfield','Metallica'),
(nextval('persons_id_seq'),'R','Malcolm','Young','AC/DC'),
(nextval('persons_id_seq'),'R','Dave','Mustaine','Megadeth'),
(nextval('persons_id_seq'),'R','Izzy','Stradlin','Guns N'' Roses'),
(nextval('persons_id_seq'),'R','Bill','Kelliher','Mastodon'),
(nextval('persons_id_seq'),'R','Tony','Iommi','Black Sabbath'),
(nextval('persons_id_seq'),'R','Chris','Cornell','Soundgarden'),
(nextval('persons_id_seq'),'R','Keith','Richards','The Rolling Stones'),
(nextval('persons_id_seq'),'R','Jerry','Cantrell','Alice in Chains'),
(nextval('persons_id_seq'),'R','Adam','Jones','Tool'),
(nextval('persons_id_seq'),'R','Dimebag','Darrell','Pantera'),
(nextval('persons_id_seq'),'R','Joe','Duplantier','Gojira'),
(nextval('persons_id_seq'),'R','Scott','Ian','Anthrax'),
(nextval('persons_id_seq'),'R','Eddie','Van Halen','Van Halen');
