INSERT INTO persons (id,band_role, first_name, last_name, band, image_name, image_thumb_name) VALUES
(nextval('persons_id_seq'),'R','James','Hetfield','Metallica','james-hetfield.png','james-hetfield-thumb.png'),
(nextval('persons_id_seq'),'R','Malcolm','Young','AC/DC','malcolm-young.png','malcolm-young-thumb.png'),
(nextval('persons_id_seq'),'R','Dave','Mustaine','Megadeth','dave-mustaine.png','dave-mustaine-thumb.png'),
(nextval('persons_id_seq'),'R','Izzy','Stradlin','Guns N'' Roses','izzy-stradlin.png','izzy-stradlin-thumb.png'),
(nextval('persons_id_seq'),'R','Bill','Kelliher','Mastodon','bill-kelliher.png','bill-kelliher-thumb.png'),
(nextval('persons_id_seq'),'R','Tony','Iommi','Black Sabbath','tony-iommi.png','tny-iommi-thumb.png'),
(nextval('persons_id_seq'),'R','Chris','Cornell','Soundgarden','chris-cornell.png','chris-cornell-thumb.png'),
(nextval('persons_id_seq'),'R','Keith','Richards','The Rolling Stones','keith-richards.png','keith-richards-thumb.png'),
(nextval('persons_id_seq'),'R','Jerry','Cantrell','Alice in Chains','jerry-cantrell.png','jerry-cantrell-thumb.png'),
(nextval('persons_id_seq'),'R','Adam','Jones','Tool','adam-jones.png','adam-jones-thumb.png'),
(nextval('persons_id_seq'),'R','Dimebag','Darrell','Pantera','dimebag-darrell.png','dimebag-darrell-thumb.png'),
(nextval('persons_id_seq'),'R','Joe','Duplantier','Gojira','joe-duplantier.png','joe-duplantier-thumb.png'),
(nextval('persons_id_seq'),'R','Scott','Ian','Anthrax','scott-ian.png','scott-ian-thumb.png'),
(nextval('persons_id_seq'),'R','Eddie','Van Halen','Van Halen','eddie-van-halen.png','eddie-van-halen-thumb.png');
