INSERT INTO persons (id,band_role, first_name, last_name, band, image_name, image_thumb_name) VALUES
(nextval('persons_id_seq'),'R','James','Hetfield','Metallica','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Malcolm','Young','AC/DC','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Dave','Mustaine','Megadeth','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Izzy','Stradlin','Guns N'' Roses','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Bill','Kelliher','Mastodon','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Tony','Iommi','Black Sabbath','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Chris','Cornell','Soundgarden','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Keith','Richards','The Rolling Stones','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Jerry','Cantrell','Alice in Chains','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Adam','Jones','Tool','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Dimebag','Darrell','Pantera','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Joe','Duplantier','Gojira','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Scott','Ian','Anthrax','todo.png','todo-thumb.png'),
(nextval('persons_id_seq'),'R','Eddie','Van Halen','Van Halen','todo.png','todo-thumb.png');
