INSERT INTO cities (id,name,state) VALUES
(nextval('cities_id_seq'),'Chicago','IL'),
(nextval('cities_id_seq'),'New Orleans','LA'),
(nextval('cities_id_seq'),'Dallas','TX'),
(nextval('cities_id_seq'),'Fort Worth','TX'),
(nextval('cities_id_seq'),'San Diego','CA'),
(nextval('cities_id_seq'),'San Francisco','CA'),
(nextval('cities_id_seq'),'Salt Lake City','UT'),
(nextval('cities_id_seq'),'Jacksonville','FL'),
(nextval('cities_id_seq'),'Indianapolis','IN'),
(nextval('cities_id_seq'),'Omaha','NE'),
(nextval('cities_id_seq'),'Grand Rapids','MI'),
(nextval('cities_id_seq'),'Boston','MA'),
(nextval('cities_id_seq'),'Sioux Falls','SD'),
(nextval('cities_id_seq'),'New York City','NY'),
(nextval('cities_id_seq'),'Minneapolis','MN'),
(nextval('cities_id_seq'),'Detroit','MI'),
(nextval('cities_id_seq'),'Topeka','KS'),
(nextval('cities_id_seq'),'Denver','CO'),
(nextval('cities_id_seq'),'Reno','NV'),
(nextval('cities_id_seq'),'Buffalo','NY'),
(nextval('cities_id_seq'),'Phoenix','AZ'),
(nextval('cities_id_seq'),'Portland','OR'),
(nextval('cities_id_seq'),'Pittsburgh','PA'),
(nextval('cities_id_seq'),'Philadelphia','PA'),
(nextval('cities_id_seq'),'Seattle','WA');
