INSERT INTO band_name_adjectives (id,value) VALUES
(nextval('band_name_adjectives_id_seq'),'Angelic'),
(nextval('band_name_adjectives_id_seq'),'Rising'),
(nextval('band_name_adjectives_id_seq'),'Lonely'),
(nextval('band_name_adjectives_id_seq'),'Deadly'),
(nextval('band_name_adjectives_id_seq'),'Wistful'),
(nextval('band_name_adjectives_id_seq'),'Ghastly'),
(nextval('band_name_adjectives_id_seq'),'Supersonic'),
(nextval('band_name_adjectives_id_seq'),'Sorrowful'),
(nextval('band_name_adjectives_id_seq'),'Perfect'),
(nextval('band_name_adjectives_id_seq'),'Charming'),
(nextval('band_name_adjectives_id_seq'),'Strawberry Death'),
(nextval('band_name_adjectives_id_seq'),'Black'),
(nextval('band_name_adjectives_id_seq'),'Blue'),
(nextval('band_name_adjectives_id_seq'),'Gray'),
(nextval('band_name_adjectives_id_seq'),'Green'),
(nextval('band_name_adjectives_id_seq'),'White'),
(nextval('band_name_adjectives_id_seq'),'Red');

INSERT INTO band_name_nouns (id,value) VALUES
(nextval('band_name_nouns_id_seq'),'Clock'),
(nextval('band_name_nouns_id_seq'),'Napkins'),
(nextval('band_name_nouns_id_seq'),'Beagles'),
(nextval('band_name_nouns_id_seq'),'Bodies'),
(nextval('band_name_nouns_id_seq'),'Puppies'),
(nextval('band_name_nouns_id_seq'),'Chipmunks'),
(nextval('band_name_nouns_id_seq'),'Socks'),
(nextval('band_name_nouns_id_seq'),'Puppet'),
(nextval('band_name_nouns_id_seq'),'Houseplants'),
(nextval('band_name_nouns_id_seq'),'Mirrors'),
(nextval('band_name_nouns_id_seq'),'Starship'),
(nextval('band_name_nouns_id_seq'),'Truckers'),
(nextval('band_name_nouns_id_seq'),'Hot Sauces'),
(nextval('band_name_nouns_id_seq'),'Clock'),
(nextval('band_name_nouns_id_seq'),'Snakes'),
(nextval('band_name_nouns_id_seq'),'Cakes');
