INSERT INTO questions (id,question,answer_string,correct_answer_index,song,band,image_name) VALUES

(nextval('questions_id_seq'),'Before she gets to saying <<BLANK>>','Hello|I love you|Goodbye|I hate you|No|Yes',2,'Ticket to Ride','The Beatles','ticket.png'),
(nextval('questions_id_seq'),'Got in a little hometown <<BLANK>>','Square|Bakery|Called Nook|Jam|Church|Fight',3,'Born in the USA','Bruce Springsteen','born.png'),
(nextval('questions_id_seq'),'Showin'' how <<BLANK>> and strong is your fight','Fair|Hard|Fierce|Aggressive|Real|Funky',5,'Beat It','Michael Jackson','beat.png'),
(nextval('questions_id_seq'),'The <<BLANK>> champagne on ice','Cold|Bottle of|New|Is No|Pink|Hot',4,'Hotel California','The Eagles','hotel.png'),
(nextval('questions_id_seq'),'For <<BLANK>> lovers','New|Old|The|Lonely|Terrible|Broken-hearted',5,'One Broken Heart For Sale','Elvis Presley','elvis.png'),
(nextval('questions_id_seq'),'Meat-eating <<BLANK>> forgive no one just yet','Orchids|Grinder|Angel|Forever|Eyes|Maggot',0,'Heart-Shaped Box','Nirvana','hshaped.png'),
(nextval('questions_id_seq'),'I''m looking to the <<BLANK>> to save me','Clock|Sky|Horizon|Hill|Man|Flag',1,'Learn To Fly','Foo Fighters','fly.png'),
(nextval('questions_id_seq'),'Fed through the <<BLANK>> that sticks in me','Mouth|Nerves|Spoon|Tube|Mind|Ego',3,'One','Metallica','one.png'),
(nextval('questions_id_seq'),'Disarm you with <<BLANK>>','Hug|Gun|This day|Loneliness|Face|A smile',5,'Disarm','Smashing Pumpkins','disarm.png'),
(nextval('questions_id_seq'),'My only comfort is the <<BLANK>> gone black','Life|Day|Night|Truth|Lies|Light',2,'I''m Only Happy When It Rains','Garbage','rains.png'),

(nextval('questions_id_seq'),'And the teeming <<BLANK>> have been terrorized','Masses|People|Creatures|Zion|City|Neighbors',0,'Vengeful','Disturbed','vengeful.png'),
(nextval('questions_id_seq'),'When I''m watchin'' <<BLANK>> and a man comes on and tells me','People|Birds|The window|Time flying|The news|My TV',5,'Satisfaction','The Rolling Stones','satisfaction.png'),
(nextval('questions_id_seq'),'I wanna be your <<BLANK>> man','Better|Best|Other|Lover|Backdoor|Only',4,'Whole Lotta Love','Led Zeppelin','led.png'),
(nextval('questions_id_seq'),'Sitting down by <<BLANK>>, looking out at the rain','Front porch|Backyard|My window|The tree|My car|The valley',2,'Ball and the Chains','Janis Joplin','ball.png'),
(nextval('questions_id_seq'),'Whatever happens, I''ll leave it all to <<BLANK>>','You|Me|Lord|God|Chance|Fate',4,'The Show Must Go On','Queen','queen.png'),
(nextval('questions_id_seq'),'Swimming through the <<BLANK>>','Void|River|Pool|Mud|Ocean|Emptiness',0,'Aerials','System of a Down','soa.png'),
(nextval('questions_id_seq'),'I got my finger on my <<BLANK>>, staring straight into a hole and I''ma get it','Head|Mouth|Ear|Leg|Pulse|Cup',4,'Cut the Cord','Shinedown','cut.png'),
(nextval('questions_id_seq'),'I was born, <<BLANK>> in my hands','Bib|A shotgun|Fate|Life|Choice|Pacifier',1,'Bad Company','Five Finger Death Punch','punch.png'),
(nextval('questions_id_seq'),'But I promise you that I''ll make sure you never <<BLANK>>','Leave me|Feel like this again|Forget me|Die|See me|Love',2,'Bulletproof','Godsmack','bullet.png'),
(nextval('questions_id_seq'),'Home alone at age <<BLANK>>','Twelve|Forty-five|Nine|Thirteen|Five|Ten',3,'Alive','Pearl Jam','pearl.png'),

(nextval('questions_id_seq'),'I heard your voice through a <<BLANK>>','Mirror|Camera|Wall|Phone|Computer|Photograph',5,'Otherside','Red Hot Chili Peppers','rhcp.png'),
(nextval('questions_id_seq'),'Hey can you hear the sound of <<BLANK>>?','Rain|Rings|Pain|Hysteria|Cars|Politics',3,'American Idiot','Green Day','green.png'),
(nextval('questions_id_seq'),'No <<BLANK>> for leaving I feel','Happiness|Relief|Sorrow or pity|Regret or pain|Loneliness|Pity',2,'I am the Highway','Audioslave','highway.png'),
(nextval('questions_id_seq'),'From the truth of <<BLANK>> lies','A hundred|A thousand|No|All the|Immense|All',1,'What I''ve Done','Linkin Park','lp.png'),
(nextval('questions_id_seq'),'Lone <<BLANK>> riding through an open space','Ranger|Gunner|Wolf|Person|Pilot|Runner',0,'R U Mine','Arctic Monkeys','monkeys.png'),
(nextval('questions_id_seq'),'So I start a revolution from my <<BLANK>>','Head|Room|Bed|Living Room|School|Neighbor',2,'Don''t Look Back in Anger','Oasis','oasis.png');
